class Special10
{
	public static void main(String args[])
	{
		int a=10,b=20,c=30,d=40,e=50,f=60,g=70,h=800,i=90,j=100;
		
		String value=(a>b)?(a>c)?(a>d)?(a>e)?(a>f)?(a>g)?(a>h)?(a>i)?(a>j)?"a is grater":"j is grater":
									(i>j)?"i is greater":"j is grater":
								(h>i)?(h>j)?"h is greater":"j is greater":
									(i>j)?"i is greater":"j is grater":
							(g>h)?(g>i)?(g>j)?"g is grater":"j is grater":
									(i>j)?"i is greater":"j is grater":
								(h>i)?(h>j)?"h is greater":"j is greater":
									(i>j)?"i is greater":"j is grater":
						(f>g)?(f>h)?(f>i)?(f>j)?"f is grater":"j is grater":
									(i>j)?"i is greater":"j is grater":
								(h>i)?(h>j)?"h is greater":"j is greater":
									(i>j)?"i is greater":"j is grater":
							(g>h)?(g>i)?(g>j)?"g is grater":"j is grater":
									(i>j)?"i is greater":"j is grater":
								(h>i)?(h>j)?"h is greater":"j is greater":
									(i>j)?"i is greater":"j is grater":
						(e>f)?(e>g)?(e>h)?(e>i)?(e>j)?"e is grater":"j is greater":
									(i>j)?"i is greater":"j is grater":
								(h>i)?(h>j)?"h is greater":"j is greater":
									(i>j)?"i is greater":"j is grater":
							(g>h)?(g>i)?(g>j)?"g is grater":"j is grater":
									(i>j)?"i is greater":"j is grater":
								(h>i)?(h>j)?"h is greater":"j is greater":
									(i>j)?"i is greater":"j is grater":
						(f>g)?(f>h)?(f>i)?(f>j)?"f is grater":"j is grater":
									(i>j)?"i is greater":"j is grater":
								(h>i)?(h>j)?"h is greater":"j is greater":
									(i>j)?"i is greater":"j is grater":
							(g>h)?(g>i)?(g>j)?"g is grater":"j is grater":
									(i>j)?"i is greater":"j is grater":
								(h>i)?(h>j)?"h is greater":"j is greater":
									(i>j)?"i is greater":"j is grater":
					(d>e)?(d>f)?(d>g)?(d>h)?(d>i)?(d>j)?"d is greater":"j is greater":
									(i>j)?"i is greater":"j is grater":
								(h>i)?(h>j)?"h is greater":"j is greater":
									(i>j)?"i is greater":"j is grater":
							(g>h)?(g>i)?(g>j)?"g is grater":"j is grater":
									(i>j)?"i is greater":"j is grater":
								(h>i)?(h>j)?"h is greater":"j is greater":
									(i>j)?"i is greater":"j is grater":
						(f>g)?(f>h)?(f>i)?(f>j)?"f is grater":"j is grater":
									(i>j)?"i is greater":"j is grater":
								(h>i)?(h>j)?"h is greater":"j is greater":
									(i>j)?"i is greater":"j is grater":
							(g>h)?(g>i)?(g>j)?"g is grater":"j is grater":
									(i>j)?"i is greater":"j is grater":
								(h>i)?(h>j)?"h is greater":"j is greater":
									(i>j)?"i is greater":"j is grater":
						(e>f)?(e>g)?(e>h)?(e>i)?(e>j)?"e is grater":"j is greater":
									(i>j)?"i is greater":"j is grater":
								(h>i)?(h>j)?"h is greater":"j is greater":
									(i>j)?"i is greater":"j is grater":
							(g>h)?(g>i)?(g>j)?"g is grater":"j is grater":
									(i>j)?"i is greater":"j is grater":
								(h>i)?(h>j)?"h is greater":"j is greater":
									(i>j)?"i is greater":"j is grater":
						(f>g)?(f>h)?(f>i)?(f>j)?"f is grater":"j is grater":
									(i>j)?"i is greater":"j is grater":
								(h>i)?(h>j)?"h is greater":"j is greater":
									(i>j)?"i is greater":"j is grater":
							(g>h)?(g>i)?(g>j)?"g is grater":"j is grater":
									(i>j)?"i is greater":"j is grater":
								(h>i)?(h>j)?"h is greater":"j is greater":
									(i>j)?"i is greater":"j is grater":
			(c>d)?(c>e)?(c>f)?(c>g)?(c>h)?(c>i)?(c>j)?"c is greater":"j is greater":
									(i>j)?"i is greater":"j is grater":
								(h>i)?(h>j)?"h is greater":"j is greater":
									(i>j)?"i is greater":"j is grater":
							(g>h)?(g>i)?(g>j)?"g is grater":"j is grater":
									(i>j)?"i is greater":"j is grater":
								(h>i)?(h>j)?"h is greater":"j is greater":
									(i>j)?"i is greater":"j is grater":
						(f>g)?(f>h)?(f>i)?(f>j)?"f is grater":"j is grater":
									(i>j)?"i is greater":"j is grater":
								(h>i)?(h>j)?"h is greater":"j is greater":
									(i>j)?"i is greater":"j is grater":
							(g>h)?(g>i)?(g>j)?"g is grater":"j is grater":
									(i>j)?"i is greater":"j is grater":
								(h>i)?(h>j)?"h is greater":"j is greater":
									(i>j)?"i is greater":"j is grater":
						(e>f)?(e>g)?(e>h)?(e>i)?(e>j)?"e is grater":"j is greater":
									(i>j)?"i is greater":"j is grater":
								(h>i)?(h>j)?"h is greater":"j is greater":
									(i>j)?"i is greater":"j is grater":
							(g>h)?(g>i)?(g>j)?"g is grater":"j is grater":
									(i>j)?"i is greater":"j is grater":
								(h>i)?(h>j)?"h is greater":"j is greater":
									(i>j)?"i is greater":"j is grater":
						(f>g)?(f>h)?(f>i)?(f>j)?"f is grater":"j is grater":
									(i>j)?"i is greater":"j is grater":
								(h>i)?(h>j)?"h is greater":"j is greater":
									(i>j)?"i is greater":"j is grater":
							(g>h)?(g>i)?(g>j)?"g is grater":"j is grater":
									(i>j)?"i is greater":"j is grater":
								(h>i)?(h>j)?"h is greater":"j is greater":
									(i>j)?"i is greater":"j is grater":
					(d>e)?(d>f)?(d>g)?(d>h)?(d>i)?(d>j)?"d is greater":"j is greater":
									(i>j)?"i is greater":"j is grater":
								(h>i)?(h>j)?"h is greater":"j is greater":
									(i>j)?"i is greater":"j is grater":
							(g>h)?(g>i)?(g>j)?"g is grater":"j is grater":
									(i>j)?"i is greater":"j is grater":
								(h>i)?(h>j)?"h is greater":"j is greater":
									(i>j)?"i is greater":"j is grater":
						(f>g)?(f>h)?(f>i)?(f>j)?"f is grater":"j is grater":
									(i>j)?"i is greater":"j is grater":
								(h>i)?(h>j)?"h is greater":"j is greater":
									(i>j)?"i is greater":"j is grater":
							(g>h)?(g>i)?(g>j)?"g is grater":"j is grater":
									(i>j)?"i is greater":"j is grater":
								(h>i)?(h>j)?"h is greater":"j is greater":
									(i>j)?"i is greater":"j is grater":
						(e>f)?(e>g)?(e>h)?(e>i)?(e>j)?"e is grater":"j is greater":
									(i>j)?"i is greater":"j is grater":
								(h>i)?(h>j)?"h is greater":"j is greater":
									(i>j)?"i is greater":"j is grater":
							(g>h)?(g>i)?(g>j)?"g is grater":"j is grater":
									(i>j)?"i is greater":"j is grater":
								(h>i)?(h>j)?"h is greater":"j is greater":
									(i>j)?"i is greater":"j is grater":
						(f>g)?(f>h)?(f>i)?(f>j)?"f is grater":"j is grater":
									(i>j)?"i is greater":"j is grater":
								(h>i)?(h>j)?"h is greater":"j is greater":
									(i>j)?"i is greater":"j is grater":
							(g>h)?(g>i)?(g>j)?"g is grater":"j is grater":
									(i>j)?"i is greater":"j is grater":
								(h>i)?(h>j)?"h is greater":"j is greater":
									(i>j)?"i is greater":"j is grater":
		(b>c)?(b>d)?(b>e)?(b>f)?(b>g)?(b>h)?(b>i)?(b>j)?"b is greater":"j is greater":
									(i>j)?"i is greater":"j is grater":
								(h>i)?(h>j)?"h is greater":"j is greater":
									(i>j)?"i is greater":"j is grater":
							(g>h)?(g>i)?(g>j)?"g is grater":"j is grater":
									(i>j)?"i is greater":"j is grater":
								(h>i)?(h>j)?"h is greater":"j is greater":
									(i>j)?"i is greater":"j is grater":
						(f>g)?(f>h)?(f>i)?(f>j)?"f is grater":"j is grater":
									(i>j)?"i is greater":"j is grater":
								(h>i)?(h>j)?"h is greater":"j is greater":
									(i>j)?"i is greater":"j is grater":
							(g>h)?(g>i)?(g>j)?"g is grater":"j is grater":
									(i>j)?"i is greater":"j is grater":
								(h>i)?(h>j)?"h is greater":"j is greater":
									(i>j)?"i is greater":"j is grater":
						(e>f)?(e>g)?(e>h)?(e>i)?(e>j)?"e is grater":"j is greater":
									(i>j)?"i is greater":"j is grater":
								(h>i)?(h>j)?"h is greater":"j is greater":
									(i>j)?"i is greater":"j is grater":
							(g>h)?(g>i)?(g>j)?"g is grater":"j is grater":
									(i>j)?"i is greater":"j is grater":
								(h>i)?(h>j)?"h is greater":"j is greater":
									(i>j)?"i is greater":"j is grater":
						(f>g)?(f>h)?(f>i)?(f>j)?"f is grater":"j is grater":
									(i>j)?"i is greater":"j is grater":
								(h>i)?(h>j)?"h is greater":"j is greater":
									(i>j)?"i is greater":"j is grater":
							(g>h)?(g>i)?(g>j)?"g is grater":"j is grater":
									(i>j)?"i is greater":"j is grater":
								(h>i)?(h>j)?"h is greater":"j is greater":
									(i>j)?"i is greater":"j is grater":
					(d>e)?(d>f)?(d>g)?(d>h)?(d>i)?(d>j)?"d is greater":"j is greater":
									(i>j)?"i is greater":"j is grater":
								(h>i)?(h>j)?"h is greater":"j is greater":
									(i>j)?"i is greater":"j is grater":
							(g>h)?(g>i)?(g>j)?"g is grater":"j is grater":
									(i>j)?"i is greater":"j is grater":
								(h>i)?(h>j)?"h is greater":"j is greater":
									(i>j)?"i is greater":"j is grater":
						(f>g)?(f>h)?(f>i)?(f>j)?"f is grater":"j is grater":
									(i>j)?"i is greater":"j is grater":
								(h>i)?(h>j)?"h is greater":"j is greater":
									(i>j)?"i is greater":"j is grater":
							(g>h)?(g>i)?(g>j)?"g is grater":"j is grater":
									(i>j)?"i is greater":"j is grater":
								(h>i)?(h>j)?"h is greater":"j is greater":
									(i>j)?"i is greater":"j is grater":
						(e>f)?(e>g)?(e>h)?(e>i)?(e>j)?"e is grater":"j is greater":
									(i>j)?"i is greater":"j is grater":
								(h>i)?(h>j)?"h is greater":"j is greater":
									(i>j)?"i is greater":"j is grater":
							(g>h)?(g>i)?(g>j)?"g is grater":"j is grater":
									(i>j)?"i is greater":"j is grater":
								(h>i)?(h>j)?"h is greater":"j is greater":
									(i>j)?"i is greater":"j is grater":
						(f>g)?(f>h)?(f>i)?(f>j)?"f is grater":"j is grater":
									(i>j)?"i is greater":"j is grater":
								(h>i)?(h>j)?"h is greater":"j is greater":
									(i>j)?"i is greater":"j is grater":
							(g>h)?(g>i)?(g>j)?"g is grater":"j is grater":
									(i>j)?"i is greater":"j is grater":
								(h>i)?(h>j)?"h is greater":"j is greater":
									(i>j)?"i is greater":"j is grater":
			(c>d)?(c>e)?(c>f)?(c>g)?(c>h)?(c>i)?(c>j)?"c is greater":"j is greater":
									(i>j)?"i is greater":"j is grater":
								(h>i)?(h>j)?"h is greater":"j is greater":
									(i>j)?"i is greater":"j is grater":
							(g>h)?(g>i)?(g>j)?"g is grater":"j is grater":
									(i>j)?"i is greater":"j is grater":
								(h>i)?(h>j)?"h is greater":"j is greater":
									(i>j)?"i is greater":"j is grater":
						(f>g)?(f>h)?(f>i)?(f>j)?"f is grater":"j is grater":
									(i>j)?"i is greater":"j is grater":
								(h>i)?(h>j)?"h is greater":"j is greater":
									(i>j)?"i is greater":"j is grater":
							(g>h)?(g>i)?(g>j)?"g is grater":"j is grater":
									(i>j)?"i is greater":"j is grater":
								(h>i)?(h>j)?"h is greater":"j is greater":
									(i>j)?"i is greater":"j is grater":
						(e>f)?(e>g)?(e>h)?(e>i)?(e>j)?"e is grater":"j is greater":
									(i>j)?"i is greater":"j is grater":
								(h>i)?(h>j)?"h is greater":"j is greater":
									(i>j)?"i is greater":"j is grater":
							(g>h)?(g>i)?(g>j)?"g is grater":"j is grater":
									(i>j)?"i is greater":"j is grater":
								(h>i)?(h>j)?"h is greater":"j is greater":
									(i>j)?"i is greater":"j is grater":
						(f>g)?(f>h)?(f>i)?(f>j)?"f is grater":"j is grater":
									(i>j)?"i is greater":"j is grater":
								(h>i)?(h>j)?"h is greater":"j is greater":
									(i>j)?"i is greater":"j is grater":
							(g>h)?(g>i)?(g>j)?"g is grater":"j is grater":
									(i>j)?"i is greater":"j is grater":
								(h>i)?(h>j)?"h is greater":"j is greater":
									(i>j)?"i is greater":"j is grater":
					(d>e)?(d>f)?(d>g)?(d>h)?(d>i)?(d>j)?"d is greater":"j is greater":
									(i>j)?"i is greater":"j is grater":
								(h>i)?(h>j)?"h is greater":"j is greater":
									(i>j)?"i is greater":"j is grater":
							(g>h)?(g>i)?(g>j)?"g is grater":"j is grater":
									(i>j)?"i is greater":"j is grater":
								(h>i)?(h>j)?"h is greater":"j is greater":
									(i>j)?"i is greater":"j is grater":
						(f>g)?(f>h)?(f>i)?(f>j)?"f is grater":"j is grater":
									(i>j)?"i is greater":"j is grater":
								(h>i)?(h>j)?"h is greater":"j is greater":
									(i>j)?"i is greater":"j is grater":
							(g>h)?(g>i)?(g>j)?"g is grater":"j is grater":
									(i>j)?"i is greater":"j is grater":
								(h>i)?(h>j)?"h is greater":"j is greater":
									(i>j)?"i is greater":"j is grater":
						(e>f)?(e>g)?(e>h)?(e>i)?(e>j)?"e is grater":"j is greater":
									(i>j)?"i is greater":"j is grater":
								(h>i)?(h>j)?"h is greater":"j is greater":
									(i>j)?"i is greater":"j is grater":
							(g>h)?(g>i)?(g>j)?"g is grater":"j is grater":
									(i>j)?"i is greater":"j is grater":
								(h>i)?(h>j)?"h is greater":"j is greater":
									(i>j)?"i is greater":"j is grater":
						(f>g)?(f>h)?(f>i)?(f>j)?"f is grater":"j is grater":
									(i>j)?"i is greater":"j is grater":
								(h>i)?(h>j)?"h is greater":"j is greater":
									(i>j)?"i is greater":"j is grater":
							(g>h)?(g>i)?(g>j)?"g is grater":"j is grater":
									(i>j)?"i is greater":"j is grater":
								(h>i)?(h>j)?"h is greater":"j is greater":
									(i>j)?"i is greater":"j is grater";
			System.out.println(value);
}}
				
			
